local s = vim.keymap.set

s({'n', 'v'}, '<leader>p', '<c-w>p', {silent = true})

s({'n', 'v'}, '<leader>w', '<cmd>:call BufferJump#Up(1)<cr>', {silent = true})
s({'n', 'v'}, '<leader>s', '<cmd>:call BufferJump#Down(1)<cr>', {silent = true})
s({'n', 'v'}, '<leader>a', '<cmd>:call BufferJump#Left(1)<cr>', {silent = true})
s({'n', 'v'}, '<leader>d', '<cmd>:call BufferJump#Right(1)<cr>', {silent = true})
s({'n', 'v'}, '2<leader>w', '<cmd>:call BufferJump#Up(2)<cr>', {silent = true})
s({'n', 'v'}, '2<leader>s', '<cmd>:call BufferJump#Down(2)<cr>', {silent = true})
s({'n', 'v'}, '2<leader>a', '<cmd>:call BufferJump#Left(2)<cr>', {silent = true})
s({'n', 'v'}, '2<leader>d', '<cmd>:call BufferJump#Right(2)<cr>', {silent = true})
s({'n', 'v'}, '3<leader>w', '<cmd>:call BufferJump#Up(3)<cr>', {silent = true})
s({'n', 'v'}, '3<leader>s', '<cmd>:call BufferJump#Down(3)<cr>', {silent = true})
s({'n', 'v'}, '3<leader>a', '<cmd>:call BufferJump#Left(3)<cr>', {silent = true})
s({'n', 'v'}, '3<leader>d', '<cmd>:call BufferJump#Right(3)<cr>', {silent = true})
s({'n', 'v'}, '4<leader>w', '<cmd>:call BufferJump#Up(4)<cr>', {silent = true})
s({'n', 'v'}, '4<leader>s', '<cmd>:call BufferJump#Down(4)<cr>', {silent = true})
s({'n', 'v'}, '4<leader>a', '<cmd>:call BufferJump#Left(4)<cr>', {silent = true})
s({'n', 'v'}, '4<leader>d', '<cmd>:call BufferJump#Right(4)<cr>', {silent = true})
s({'n', 'v'}, '5<leader>w', '<cmd>:call BufferJump#Up(5)<cr>', {silent = true})
s({'n', 'v'}, '5<leader>s', '<cmd>:call BufferJump#Down(5)<cr>', {silent = true})
s({'n', 'v'}, '5<leader>a', '<cmd>:call BufferJump#Left(5)<cr>', {silent = true})
s({'n', 'v'}, '5<leader>d', '<cmd>:call BufferJump#Right(5)<cr>', {silent = true})
s({'n', 'v'}, '6<leader>w', '<cmd>:call BufferJump#Up(6)<cr>', {silent = true})
s({'n', 'v'}, '6<leader>s', '<cmd>:call BufferJump#Down(6)<cr>', {silent = true})
s({'n', 'v'}, '6<leader>a', '<cmd>:call BufferJump#Left(6)<cr>', {silent = true})
s({'n', 'v'}, '6<leader>d', '<cmd>:call BufferJump#Right(6)<cr>', {silent = true})
s({'n', 'v'}, '7<leader>w', '<cmd>:call BufferJump#Up(7)<cr>', {silent = true})
s({'n', 'v'}, '7<leader>s', '<cmd>:call BufferJump#Down(7)<cr>', {silent = true})
s({'n', 'v'}, '7<leader>a', '<cmd>:call BufferJump#Left(7)<cr>', {silent = true})
s({'n', 'v'}, '7<leader>d', '<cmd>:call BufferJump#Right(7)<cr>', {silent = true})
s({'n', 'v'}, '8<leader>w', '<cmd>:call BufferJump#Up(8)<cr>', {silent = true})
s({'n', 'v'}, '8<leader>s', '<cmd>:call BufferJump#Down(8)<cr>', {silent = true})
s({'n', 'v'}, '8<leader>a', '<cmd>:call BufferJump#Left(8)<cr>', {silent = true})
s({'n', 'v'}, '8<leader>d', '<cmd>:call BufferJump#Right(8)<cr>', {silent = true})
s({'n', 'v'}, '9<leader>w', '<cmd>:call BufferJump#Up(9)<cr>', {silent = true})
s({'n', 'v'}, '9<leader>s', '<cmd>:call BufferJump#Down(9)<cr>', {silent = true})
s({'n', 'v'}, '9<leader>a', '<cmd>:call BufferJump#Left(9)<cr>', {silent = true})
s({'n', 'v'}, '9<leader>d', '<cmd>:call BufferJump#Right(9)<cr>', {silent = true})

s({'n', 'v'}, '<leader>o', '<cmd>:call BufferJump#MaxHeight()<cr>', {silent = true})
s({'n', 'v'}, '<leader>i', '<cmd>:call BufferJump#SameWidthHeight()<cr>', {silent = true})
s({'n', 'v'}, '<leader>u', '<cmd>:call BufferJump#MaxWidth()<cr>', {silent = true})

s({'n', 'v'}, '<leader><leader>o', '<cmd>:call BufferJump#Miximize(1)<cr>', {silent = true})
s({'n', 'v'}, '<leader><leader>i', '<cmd>:call BufferJump#Miximize(0)<cr>', {silent = true})

s({'n', 'v'}, '<leader><leader><leader>i', '<cmd>:call BufferJump#SameWidthHeightFix()<cr>', {silent = true})

s({'n', 'v'}, '<leader><leader>w', '<cmd>:call BufferJump#WinFixHeight()<cr>', {silent = true})
s({'n', 'v'}, '<leader><leader>s', '<cmd>:call BufferJump#NoWinFixHeight()<cr>', {silent = true})
s({'n', 'v'}, '<leader><leader>d', '<cmd>:call BufferJump#WinFixWidth()<cr>', {silent = true})
s({'n', 'v'}, '<leader><leader>a', '<cmd>:call BufferJump#NoWinFixWidth()<cr>', {silent = true})
