local s = vim.keymap.set

s({ 'n', 'v', }, '<C-j>', '5j')
s({ 'n', 'v', }, '<C-k>', '5k')
s({ 't', 'c', 'i' }, '<A-k>', '<UP>')
s({ 't', 'c', 'i' }, '<A-j>', '<DOWN>')
s({ 't', 'c', 'i' }, '<A-S-k>', '<UP><UP><UP><UP><UP>')
s({ 't', 'c', 'i' }, '<A-S-j>', '<DOWN><DOWN><DOWN><DOWN><DOWN>')
s({ 't', 'c', 'i' }, '<A-i>', '<HOME>')
s({ 't', 'c', 'i' }, '<A-S-i>', '<HOME>')
s({ 't', 'c', 'i' }, '<A-o>', '<END>')
s({ 't', 'c', 'i' }, '<A-S-o>', '<END>')
s({ 't', 'c', 'i' }, '<A-l>', '<RIGHT>')
s({ 't', 'c', 'i' }, '<A-h>', '<LEFT>')
s({ 't', 'c', 'i' }, '<A-S-l>', '<RIGHT><RIGHT><RIGHT><RIGHT><RIGHT>')
s({ 't', 'c', 'i' }, '<A-S-h>', '<LEFT><LEFT><LEFT><LEFT><LEFT>')
s({ 'v', }, '<C-l>', 'L')
s({ 'v', }, '<C-h>', 'H')
s({ 'v', }, '<C-g>', 'G')
s({ 'v', }, '<C-m>', 'M')
