local o = vim.opt

o.number = true
o.relativenumber = true
o.title = true
o.updatetime = 0
o.winminheight = 0
o.winminwidth = 0
o.expandtab = true
o.autoindent = true
o.smartindent = true
o.wrap = false
o.smartcase = true
o.cursorline = true
o.termguicolors = true
o.background = "dark"
o.signcolumn = "yes"
o.backspace = "indent,eol,start"
o.splitright = true
o.splitbelow = true
o.mousemodel = "extend"
o.swapfile = false
o.iskeyword = '@,48-57,_,192-255'
o.fileformats = 'dos'
o.foldmethod = "indent"
